# Generated by Django 4.2.30 on 2026-08-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du département')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code département')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Intitulé du poste')),
                ('base_salary_min', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire min (FCFA/€)')),
                ('base_salary_max', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire max (FCFA/€)')),
                ('description', models.TextField(blank=True, verbose_name='Missions et responsabilités')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employees.department', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text="Identifiant unique de l'employé (ex: EMP-2026-001)", max_length=20, unique=True, verbose_name='Matricule')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], default='M', max_length=1, verbose_name='Genre')),
                ('marital_status', models.CharField(choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf/Veuve')], default='CELIBATAIRE', max_length=20, verbose_name='Statut matrimonial')),
                ('address', models.TextField(blank=True, verbose_name='Adresse résidentielle')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name="Contact d'urgence (Nom)")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name="Contact d'urgence (Tél)")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('contract_type', models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée (CDI)'), ('CDD', 'Contrat à Durée Déterminée (CDD)'), ('STAGE', 'Stage'), ('FREELANCE', 'Freelance / Prestatation'), ('INTERIM', 'Intérim')], default='CDI', max_length=20, verbose_name='Type de contrat')),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('EN_CONGE', 'En congé'), ('SUSPENDU', 'Suspendu'), ('DEMISSIONNE', 'Démissionné'), ('LICENCIE', 'Licencié')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('hire_date', models.DateField(verbose_name="Date d'embauche")),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Fin de contrat (si applicable)')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire de base')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department', verbose_name='Département')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='Superviseur Hiérarchique')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position', verbose_name='Poste / Fonction')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='employees.employee', verbose_name='Responsable de département'),
        ),
    ]
