# Generated by Django 6.1 on 2026-08-23 16:41

import django.db.models.deletion
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom de la banque'),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('INCONNU', 'Non renseigné')], default='INCONNU', max_length=10, verbose_name='Groupe sanguin'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lien de parenté / Relation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='iban',
            field=models.CharField(blank=True, max_length=40, verbose_name='IBAN / Numéro de compte'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° CNI / Passeport / Sécurité Sociale'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default='Française', max_length=50, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes administratives RH'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Adresse Email Personnelle'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name="Fin période d'essai"),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.CharField(blank=True, help_text='Ex: Python, Django, Leadership, Recrutement (séparés par des virgules)', max_length=255, verbose_name='Compétences clés'),
        ),
        migrations.AddField(
            model_name='employee',
            name='swift_bic',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code SWIFT / BIC'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de contrat (si CDD/Stage)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée (CDI)'), ('CDD', 'Contrat à Durée Déterminée (CDD)'), ('STAGE', 'Stage conventionné'), ('APPRENTISSAGE', "Contrat d'apprentissage / Alternance"), ('FREELANCE', 'Freelance / Prestation externe'), ('INTERIM', 'Intérim')], default='CDI', max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email Professionnelle'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=25, verbose_name="Contact d'urgence (Tél)"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('PACSE', 'Pacsé(e)'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf/Veuve')], default='CELIBATAIRE', max_length=20, verbose_name='Statut matrimonial'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registration_number',
            field=models.CharField(help_text='Identifiant unique (généré automatiquement si vide)', max_length=30, unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('EN_CONGE', 'En congé'), ('EN_FORMATION', 'En formation'), ('SUSPENDU', 'Suspendu'), ('DEMISSIONNE', 'Démissionné'), ('LICENCIE', 'Licencié'), ('RETRAITE', 'Retraité')], default='ACTIF', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Intitulé du document')),
                ('document_type', models.CharField(choices=[('CONTRAT', 'Contrat de travail'), ('AVENANT', 'Avenant au contrat'), ('CNI_PASSEPORT', "Pièce d'identité / Passeport"), ('CV', 'Curriculum Vitae (CV)'), ('DIPLOME', 'Diplôme / Certification'), ('VISITE_MEDICALE', 'Certificat visite médicale'), ('EVALUATION', "Fiche d'évaluation / Entretien"), ('RIB', "Relevé d'Identité Bancaire (RIB)"), ('AUTRE', 'Autre document RH')], default='AUTRE', max_length=30, verbose_name='Type de document')),
                ('file', models.FileField(upload_to=employees.models.employee_document_upload_path, verbose_name='Fichier')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration (si applicable)")),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléversement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Document employé',
                'verbose_name_plural': 'Documents employés',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
