# Generated by Django 4.2.30 on 2026-08-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois')),
                ('year', models.IntegerField(default=2026, verbose_name='Année')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire de base')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prime de transport')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Indemnité de logement')),
                ('performance_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prime de performance')),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impôt sur le revenu (IRPP)')),
                ('social_security_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cotisations sociales (CNSS)')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Autres déductions')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire brut')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire net à payer')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('payment_method', models.CharField(choices=[('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces')], default='VIREMENT', max_length=20, verbose_name='Mode de paiement')),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('PAYE', 'Payé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
