# Generated by Django 4.2.30 on 2026-08-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time_in', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('RETARD', 'En retard'), ('ABSENT', 'Absent'), ('DEMI_JOURNEE', 'Demi-journée'), ('CONGE', 'En congé')], default='PRESENT', max_length=20, verbose_name='Statut')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observations')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pointage / Présence',
                'verbose_name_plural': 'Pointages & Présences',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
